import React, { Component } from 'react'
// import slider1 from '../homepage05-slide1.jpg'
// import slider2 from '../homepage05-slide2.jpg'
// import slider3 from '../homepage05-slide3.jpg'

export default class Slider extends Component {
    render() {
        return (
            <div className="hero-slider-area section-space">
                <div id="rev_slider_26_1" className="rev_slider fullscreenbanner" style={{ display: 'none' }} data-version="5.4.7">
                    <ul>

                        <li data-index="rs-62" data-transition="slideoverdown,slidingoverlayvertical,cube-horizontal,3dcurtain-vertical" data-slotamount="default,default,default,default" data-hideafterloop={0} data-hideslideonmobile="off" data-easein="default,default,default,default" data-easeout="default,default,default,default" data-masterspeed="980,default,default,default" data-thumb data-delay={7010} data-rotate="0,0,0,0" data-saveperformance="off" data-title="Slide" data-param1 data-param2 data-param3 data-param4 data-param5 data-param6 data-param7 data-param8 data-param9 data-param10 data-description>

                            <img src={"slider1"} alt="" width={1920} height={1080} data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" className="rev-slidebg" data-no-retina />

                            <div className="tp-caption   tp-resizeme" id="slide-62-layer-3" data-x="['center','center','center','center']" data-hoffset="['0','0','5','0']" data-y="['top','top','top','top']" data-voffset="['213','196','340','228']" data-color="['rgba(17,17,17,0.4)','rgb(0,0,0)','rgb(0,0,0)','rgb(0,0,0)']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:640,&quot;speed&quot;:1310,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;x:[-175%];y:0px;z:0;rX:0;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:1;&quot;,&quot;mask&quot;:&quot;x:[100%];y:0;s:inherit;e:inherit;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 5, whiteSpace: 'nowrap', fontSize: '22px', lineHeight: '35px', fontWeight: 700, color: 'rgba(17,17,17,0.4)', letterSpacing: '1px', fontFamily: 'Source Sans Pro' }}>
                                NEW COLLECTION 2019 </div>

                            <div className="tp-caption   tp-resizeme" id="slide-62-layer-5" data-x="['center','center','center','center']" data-hoffset="['1','7','-4','0']" data-y="['top','middle','middle','middle']" data-voffset="['281','-39','-8','-21']" data-fontsize="['60','60','60','50']" data-lineheight="['60','70','60','55']" data-fontweight="['600','400','400','400']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:410,&quot;speed&quot;:1950,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;x:[175%];y:0px;z:0;rX:0;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:1;&quot;,&quot;mask&quot;:&quot;x:[-100%];y:0;s:inherit;e:inherit;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power2.easeInOut&quot;}]" data-textalign="['center','center','center','center']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 6, whiteSpace: 'nowrap', fontSize: '60px', lineHeight: '60px', fontWeight: 600, color: '#000000', letterSpacing: '-2px', fontFamily: 'Source Sans Pro' }}>
                                New Interior Concept<br />
                                Wooden Chairs </div>

                            <a className="tp-caption Robin-Button-New rev-btn " href="shop-left-sidebar.html" target="_self" id="slide-62-layer-7" data-x="['center','center','center','center']" data-hoffset="['0','0','3','4']" data-y="['top','middle','top','top']" data-voffset="['447','94','580','417']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="button" data-actions data-responsive_offset="on" data-responsive="off" data-frames="[{&quot;delay&quot;:890,&quot;speed&quot;:1040,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power4.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;nothing&quot;},{&quot;frame&quot;:&quot;hover&quot;,&quot;speed&quot;:&quot;300&quot;,&quot;ease&quot;:&quot;Power0.easeInOut&quot;,&quot;to&quot;:&quot;o:1;rX:0;rY:0;rZ:0;z:0;&quot;,&quot;style&quot;:&quot;c:rgb(255,255,255);bg:rgb(34,34,34);bc:rgb(0,0,0);&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[12,12,12,12]" data-paddingright="[25,25,25,25]" data-paddingbottom="[12,12,12,12]" data-paddingleft="[25,25,25,25]" style={{ zIndex: 7, whiteSpace: 'nowrap', fontSize: '16px', lineHeight: '21px', fontWeight: 700, color: '#000000', fontFamily: 'Source Sans Pro', backgroundColor: 'rgba(247,177,19,0)', borderColor: 'rgba(0,0,0,1)', borderStyle: 'solid', borderWidth: '2px 2px 2px 2px', borderRadius: '5px 5px 5px 5px', outline: 'none', boxShadow: 'none', boxSizing: 'border-box', MozBoxSizing: 'border-box', WebkitBoxSizing: 'border-box', cursor: 'pointer', textDecoration: 'none' }}>SHOP
                                NOW!
                            </a>
                        </li>

                        <li data-index="rs-63" data-transition="parallaxtoright,parallaxtoleft,parallaxtotop,parallaxtobottom,parallaxhorizontal,slidingoverlaydown,slidingoverlayleft,slidingoverlayright,slidingoverlayhorizontal" data-slotamount="default,default,default,default,default,default,default,default,default" data-hideafterloop={0} data-hideslideonmobile="off" data-easein="default,default,default,default,default,default,default,default,default" data-easeout="default,default,default,default,default,default,default,default,default" data-masterspeed="1000,default,default,default,default,default,default,default,default" data-thumb data-delay={7000} data-rotate="0,0,0,0,0,0,0,0,0" data-saveperformance="off" data-title="Slide" data-param1 data-param2 data-param3 data-param4 data-param5 data-param6 data-param7 data-param8 data-param9 data-param10 data-description>

                            <img src={"slider2"} alt="" width={1920} height={1080} data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" className="rev-slidebg" data-no-retina />

                            <div className="tp-caption   tp-resizeme" id="slide-63-layer-9" data-x="['center','center','center','center']" data-hoffset="['2','0','-6','4']" data-y="['top','top','top','top']" data-voffset="['253','255','338','230']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:290,&quot;speed&quot;:2000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power4.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Back.easeIn&quot;}]" data-textalign="['center','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 5, whiteSpace: 'nowrap', fontSize: '22px', lineHeight: '35px', fontWeight: 700, color: 'rgba(17,17,17,0.4)', letterSpacing: '0px', fontFamily: 'Source Sans Pro' }}>
                                NEW COLLECTION 2019
                            </div>

                            <div className="tp-caption   tp-resizeme" id="slide-63-layer-5" data-x="['center','center','center','center']" data-hoffset="['1','3','4','10']" data-y="['middle','middle','middle','middle']" data-voffset="['-1','0','0','0']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:520,&quot;speed&quot;:2000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power4.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Back.easeIn&quot;}]" data-textalign="['center','center','center','center']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 6, whiteSpace: 'nowrap', fontSize: '60px', lineHeight: '60px', fontWeight: 600, color: '#000000', letterSpacing: '-2px', fontFamily: 'Source Sans Pro' }}>
                                The Brighten Up<br />
                                Interior Collection </div>

                            <a className="tp-caption Robin-Button-New rev-btn " href="shop-left-sidebar.html" target="_self" id="slide-63-layer-7" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['top','middle','top','top']" data-voffset="['489','126','589','465']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="button" data-actions data-responsive_offset="on" data-responsive="off" data-frames="[{&quot;delay&quot;:1080,&quot;speed&quot;:940,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;y:-50px;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power4.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power2.easeInOut&quot;},{&quot;frame&quot;:&quot;hover&quot;,&quot;speed&quot;:&quot;400&quot;,&quot;ease&quot;:&quot;Power4.easeInOut&quot;,&quot;to&quot;:&quot;o:1;rX:0;rY:0;rZ:0;z:0;&quot;,&quot;style&quot;:&quot;c:rgb(255,255,255);bg:rgb(34,34,34);bc:rgb(0,0,0);&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[12,12,12,12]" data-paddingright="[25,25,25,25]" data-paddingbottom="[12,12,12,12]" data-paddingleft="[25,25,25,25]" style={{ zIndex: 7, whiteSpace: 'nowrap', fontSize: '16px', lineHeight: '21px', fontWeight: 700, color: '#000000', fontFamily: 'Source Sans Pro', backgroundColor: 'rgba(247,177,19,0)', borderColor: 'rgba(0,0,0,1)', borderStyle: 'solid', borderWidth: '2px 2px 2px 2px', borderRadius: '5px 5px 5px 5px', outline: 'none', boxShadow: 'none', boxSizing: 'border-box', MozBoxSizing: 'border-box', WebkitBoxSizing: 'border-box', cursor: 'pointer', textDecoration: 'none' }}>SHOP
                                NOW!
                            </a>
                        </li>

                        <li data-index="rs-64" data-transition="parallaxtoright,parallaxtoleft,parallaxtotop,parallaxtobottom,parallaxhorizontal,slidingoverlaydown,slidingoverlayleft,slidingoverlayright,slidingoverlayhorizontal" data-slotamount="default,default,default,default,default,default,default,default,default" data-hideafterloop={0} data-hideslideonmobile="off" data-easein="default,default,default,default,default,default,default,default,default" data-easeout="default,default,default,default,default,default,default,default,default" data-masterspeed="1000,default,default,default,default,default,default,default,default" data-thumb data-delay={7000} data-rotate="0,0,0,0,0,0,0,0,0" data-saveperformance="off" data-title="Slide" data-param1 data-param2 data-param3 data-param4 data-param5 data-param6 data-param7 data-param8 data-param9 data-param10 data-description>

                            <img src={"slider3"} alt="" width={1920} height={1080} data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" className="rev-slidebg" data-no-retina />
                            <div className="tp-caption   tp-resizeme" id="slide-64-layer-9" data-x="['center','center','center','center']" data-hoffset="['0','8','13','0']" data-y="['top','top','top','top']" data-voffset="['287','281','387','269']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:500,&quot;speed&quot;:2000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;x:[-175%];y:0px;z:0;rX:0;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:1;&quot;,&quot;mask&quot;:&quot;x:[100%];y:0;s:inherit;e:inherit;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Back.easeIn&quot;}]" data-textalign="['center','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 5, whiteSpace: 'nowrap', fontSize: '22px', lineHeight: '35px', fontWeight: 700, color: 'rgba(17,17,17,0.4)', letterSpacing: '0px', fontFamily: 'Source Sans Pro' }}>
                                NEW COLLECTION 2019
                            </div>
                            <div className="tp-caption   tp-resizeme" id="slide-64-layer-5" data-x="['center','center','center','center']" data-hoffset="['0','3','4','9']" data-y="['middle','middle','middle','middle']" data-voffset="['0','0','0','0']" data-fontsize="['60','60','60','40']" data-lineheight="['60','60','60','50']" data-letterspacing="['-2','-2','-2','0']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:500,&quot;speed&quot;:2000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;x:[175%];y:0px;z:0;rX:0;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:1;&quot;,&quot;mask&quot;:&quot;x:[-100%];y:0;s:inherit;e:inherit;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Back.easeIn&quot;}]" data-textalign="['center','center','center','center']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 6, whiteSpace: 'nowrap', fontSize: '60px', lineHeight: '60px', fontWeight: 600, color: '#000000', letterSpacing: '-2px', fontFamily: 'Source Sans Pro' }}>
                                The Marble Concept </div>
                            <a className="tp-caption Robin-Button-New rev-btn " href="shop-left-sidebar.html" target="_self" id="slide-64-layer-7" data-x="['center','center','center','center']" data-hoffset="['0','4','13','0']" data-y="['top','middle','top','top']" data-voffset="['463','102','552','431']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="button" data-actions data-responsive_offset="on" data-responsive="off" data-frames="[{&quot;delay&quot;:930,&quot;speed&quot;:940,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;y:-50px;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power4.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power2.easeInOut&quot;},{&quot;frame&quot;:&quot;hover&quot;,&quot;speed&quot;:&quot;400&quot;,&quot;ease&quot;:&quot;Power4.easeInOut&quot;,&quot;to&quot;:&quot;o:1;rX:0;rY:0;rZ:0;z:0;&quot;,&quot;style&quot;:&quot;c:rgb(255,255,255);bg:rgb(34,34,34);bc:rgb(0,0,0);&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[12,12,12,12]" data-paddingright="[25,25,25,25]" data-paddingbottom="[12,12,12,12]" data-paddingleft="[25,25,25,25]" style={{ zIndex: 7, whiteSpace: 'nowrap', fontSize: '16px', lineHeight: '21px', fontWeight: 700, color: '#000000', fontFamily: 'Source Sans Pro', backgroundColor: 'rgba(247,177,19,0)', borderColor: 'rgba(0,0,0,1)', borderStyle: 'solid', borderWidth: '2px 2px 2px 2px', borderRadius: '5px 5px 5px 5px', outline: 'none', boxShadow: 'none', boxSizing: 'border-box', MozBoxSizing: 'border-box', WebkitBoxSizing: 'border-box', cursor: 'pointer', textDecoration: 'none' }}>SHOP
                                NOW!
                            </a>
                        </li>
                    </ul>
                    <div className="tp-bannertimer tp-bottom" style={{ visibility: 'hidden !important' }} />
                </div>
            </div>

        )
    }
}
